---
#- name: Pull image from dockerhub
#  hosts: jenkins
#  tasks:
#    - name: Install pip requests library
#      pip:
#        name: requests
#        state: present
#
#    - name: Pull calculator image
#      docker_image:
#        name: lovyparhar/java-calculator-devops:1.0
#        source: pull
- name: Pull image from dockerhub
  hosts: server
  tasks:
    - name: Pull calculator image
      docker_image:
        name: lovyparhar/java-calculator-devops:1.0
        source: pull
