---
#- name: Pull image from dockerhub
#  hosts: jenkins
#  tasks:
#    - name: Install pip requests library
#      pip:
#        name: requests
#        state: present
#
#    - name: Pull calculator image
#      docker_image:
#        name: lovyparhar/java-calculator-devops:1.0
#        source: pull
- name: Pull image from dockerhub
  hosts: server
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Stop and remove the current container
      shell: docker ps -aq | xargs docker stop | xargs docker rm

    - name: Pull calculator image
      docker_image:
        name: lovyparhar/java-calculator-devops:latest
        source: pull

    - name: Run the new docker container
      shell: docker run -d -it --name calculator lovyparhar/java-calculator-devops:latest
